ci: add protoc on build
So... this shouldn't be necessary. `protoc` is needed to build the files
in `net` like `net/lp_rpc.pb.go`. Those files are committed to the repo;
`make` shouldn't be rebuilding them. And yet, every so often, we get an
error on build that [looks like this](https://github.com/livepeer/go-livepeer/actions/runs/6630250258/job/18011282601?pr=2886):

```
protoc -I=. --go_out=plugins=grpc:. net/lp_rpc.proto
/bin/bash: line 1: protoc: command not found
make: *** [Makefile:7: net/lp_rpc.pb.go] Error 127
Error: Process completed with exit code 2.
```

I don't know why that happens. It doesn't happen once you rebuild. But...
regenerating those files is harmless, I guess, so this will stop that
for everybody forever. IDK.